apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://3.8.148.214/api"
  NEXTAUTH_URL: "http://3.8.148.214"
  NEXTAUTH_SECRET: "eOTiajYI2SDw4YZLvCUO4F5sNsqq6LG+DpmSXg2Nm8s="
  JWT_SECRET: "ca044bb5c4cb31442779b63679f40fc11fbb3d5d5a12c62fc701867e8190a3ea"
