apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secret
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "ca044bb5c4cb31442779b63679f40fc11fbb3d5d5a12c62fc701867e8190a3ea"
  NEXTAUTH_SECRET: "eOTiajYI2SDw4YZLvCUO4F5sNsqq6LG+DpmSXg2Nm8s="
